// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-0bekr0Kn1iNvZGpZiuzbEC8NSnzwNtQ',
    appId: '1:748832370596:web:4289376900cf83cc1d5b31',
    messagingSenderId: '748832370596',
    projectId: 'angular-ecommerce-94b8b',
    authDomain: 'angular-ecommerce-94b8b.firebaseapp.com',
    databaseURL: 'https://angular-ecommerce-94b8b.firebaseio.com',
    storageBucket: 'angular-ecommerce-94b8b.firebasestorage.app',
    measurementId: 'G-B76P4R4LM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBajaZ3qGTrZUGPbOSmHckPLES9PfqmLzc',
    appId: '1:748832370596:android:ea1de33d635322ea1d5b31',
    messagingSenderId: '748832370596',
    projectId: 'angular-ecommerce-94b8b',
    databaseURL: 'https://angular-ecommerce-94b8b.firebaseio.com',
    storageBucket: 'angular-ecommerce-94b8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABitTVUlMyFMQA-088DI1Dv-B-gpWlFL4',
    appId: '1:748832370596:ios:daa252cf0c9d54c51d5b31',
    messagingSenderId: '748832370596',
    projectId: 'angular-ecommerce-94b8b',
    databaseURL: 'https://angular-ecommerce-94b8b.firebaseio.com',
    storageBucket: 'angular-ecommerce-94b8b.firebasestorage.app',
    iosClientId: '748832370596-b9826dgm4b79hlk4q945mlgh9mhejffl.apps.googleusercontent.com',
    iosBundleId: 'com.notestaker.sandberg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABitTVUlMyFMQA-088DI1Dv-B-gpWlFL4',
    appId: '1:748832370596:ios:daa252cf0c9d54c51d5b31',
    messagingSenderId: '748832370596',
    projectId: 'angular-ecommerce-94b8b',
    databaseURL: 'https://angular-ecommerce-94b8b.firebaseio.com',
    storageBucket: 'angular-ecommerce-94b8b.firebasestorage.app',
    iosClientId: '748832370596-b9826dgm4b79hlk4q945mlgh9mhejffl.apps.googleusercontent.com',
    iosBundleId: 'com.notestaker.sandberg',
  );
}
